sdks/bk-storages/CHANGE.md
sdks/bk-storages/bkstorages/backends/bkrepo.py
sdks/bk-storages/bkstorages/backends/rgw.py
sdks/bk-storages/bkstorages/utils.py
sdks/bk-storages/pyproject.toml
sdks/bk-storages/setup.py
sdks/bk-storages/tests/models.py
sdks/bk-storages/tests/test_bkrepo.py
sdks/bk-storages/tests/test_rgw.py

close https://github.com/TencentBlueKing/bkpaas-python-sdk/issues/6

bugfix: 修复 file_overwrite 在 BKRepoStorage 中不生效的问题

---

sdks/apigw-manager/CHANGE.md
sdks/apigw-manager/Makefile
sdks/bkapi-client-core/.gitignore
sdks/bkapi-client-core/CHANGE.md
sdks/bkapi-client-core/Makefile

- apigw-manager Makefile 支持 publish 到 pypi 源

Makefile support publish sdk to pypi

---

sdks/bk-storages/CHANGE.md
sdks/bk-storages/bkstorages/__init__.py
sdks/bk-storages/bkstorages/backends/bkrepo.py
sdks/bk-storages/bkstorages/exceptions.py
sdks/bk-storages/pyproject.toml
sdks/bk-storages/setup.py
sdks/blue-krill/CHANGE.md
sdks/blue-krill/blue_krill/__init__.py
sdks/blue-krill/blue_krill/storages/blobstore/base.py
sdks/blue-krill/blue_krill/storages/blobstore/bkrepo.py
sdks/blue-krill/blue_krill/storages/blobstore/exceptions.py
sdks/blue-krill/blue_krill/storages/blobstore/s3.py
sdks/blue-krill/pyproject.toml
sdks/blue-krill/setup.py
sdks/blue-krill/tests/storages/test_bkrepo.py
sdks/blue-krill/tests/storages/test_s3.py

enhance: `blue_krill.storages.blobstore` 增加 `DownloadFailedError` 和 `UploadFailedError` 异常
minor: 调整调试信息的日志级别

enhance: `blue_krill.storages.blobstore` 增加 `DownloadFailedError` 和 `UploadFailedError` 异常

---

sdks/apigw-manager/demo/settings.py
sdks/apigw-manager/demo/views.py
sdks/apigw-manager/poetry.lock
sdks/apigw-manager/pyproject.toml
sdks/apigw-manager/src/apigw_manager/apigw/apps.py
sdks/apigw-manager/src/apigw_manager/core/exceptions.py
sdks/apigw-manager/src/apigw_manager/core/fetch.py
sdks/apigw-manager/src/apigw_manager/core/handler.py
sdks/apigw-manager/src/apigw_manager/core/permission.py
sdks/apigw-manager/src/apigw_manager/core/release.py
sdks/apigw-manager/src/apigw_manager/core/sync.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_authentication.py
sdks/apigw-manager/tests/apigw_manager/core/test_hander.py
sdks/apigw-manager/tests/demo/test_views.py

优化报错可读性以及兼容 Django 3.X

---

.github/workflows/python.yml
sdks/blue-krill/blue_krill/monitoring/probe/tcp.py
sdks/blue-krill/poetry.lock
sdks/blue-krill/pyproject.toml
sdks/blue-krill/tests/monitoring/probe/test_http.py
sdks/blue-krill/tests/monitoring/probe/test_tcp.py
sdks/blue-krill/tests/storages/test_bkrepo.py
sdks/blue-krill/tests/storages/test_s3.py
sdks/blue-krill/tests/test_redis_tools.py
sdks/blue-krill/tox.ini

修复 github action 并增加单元测试环节

---

sdks/apigw-manager/.pre-commit-config.yaml
sdks/apigw-manager/pyproject.toml
sdks/apigw-manager/src/apigw_manager/apigw/admin.py
sdks/apigw-manager/src/apigw_manager/apigw/authentication.py
sdks/apigw-manager/src/apigw_manager/apigw/helper.py
sdks/apigw-manager/src/apigw_manager/apigw/management/commands/fetch_apigw_public_key.py
sdks/apigw-manager/src/apigw_manager/core/fetch.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_authentication.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_helper.py

support jwt issuer

---

sdks/apigw-manager/src/apigw_manager/apigw/command.py
sdks/apigw-manager/src/apigw_manager/apigw/management/commands/create_version_and_release_apigw.py
sdks/apigw-manager/src/apigw_manager/apigw/utils.py
sdks/apigw-manager/tests/apigw_manager/apigw/management/commands/test_create_version_and_release_apigw.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_utils.py

- 修复 apigw-manager 创建资源版本时，部分情况创建版本失败的问题
- 优化 host 获取

Fix create resource version

---

.pre-commit-config.yaml
sdks/blue-krill/blue_krill/web/std_error.py
sdks/blue-krill/tests/web/test_std_error.py

web.str_error 兼容延迟加载的字符串，比如django国际化翻译

feat(web str error): support lazy str, such as django i18n gettext

---

.pre-commit-config.yaml

修复pre-commit 敏感信息检查hook不支持 pre-commit参数问题（无法增量检查、指定目录、忽略文件）

ci(pre-commit): sensitive info check support pre-commit args

---

readme.md
readme_en.md

Remove links of BCS-SaaS from README

Remove links of BCS-SaaS from README

---

readme.md
readme_en.md
sdks/bkapi-component-open/CHANGE.md
sdks/bkapi-component-open/bkapi_component/open/__init__.py
sdks/bkapi-component-open/bkapi_component/open/client.py
sdks/bkapi-component-open/bkapi_component/open/client.pyi
sdks/bkapi-component-open/bkapi_component/open/shortcuts.py
sdks/bkapi-component-open/setup.py

- 添加 cc, itsm, monitor_v3, sops 组件 API
- 删除 monitor_v3 部分组件 API

更新 sdk bkapi-component-open，添加组件 API

---

.github/workflows/bkpaas-auth.yml

ci: fix workflow

---

sdks/bkpaas-auth/CHANGES.md
sdks/bkpaas-auth/bkpaas_auth/__init__.py
sdks/bkpaas-auth/bkpaas_auth/core/token.py
sdks/bkpaas-auth/pyproject.toml
sdks/bkpaas-auth/setup.py

feat: tokenRequestBackend.request_username support i18n

---

.github/workflows/blue-krill.yml

fix:poetry version

---

sdks/apigw-manager/CHANGE.md
sdks/apigw-manager/demo/bin/sync-apigateway
sdks/apigw-manager/pyproject.toml

- 修复 sync-apigateway 在后端接口失败时未退出的问题

修复 sync-apigateway 在后端接口失败时未退出的问题

---

sdks/blue-krill/CHANGE.md

doc:change logs

---

.github/workflows/blue-krill.yml

fix: blue-krill build workflow does not work beacuse spelling error

---

sdks/blue-krill/CHANGE.md
sdks/blue-krill/blue_krill/encrypt/handler.py
sdks/blue-krill/pyproject.toml
sdks/blue-krill/tests/test_encrypt.py

Fix: configure the correct SM4 encryption algorithm

Fix: configure the correct SM4 encryption algorithm

---

sdks/apigw-manager/pyproject.toml
sdks/bk-storages/pyproject.toml
sdks/bkapi-client-core/pyproject.toml
sdks/bkapi-component-open/setup.py
sdks/bkpaas-auth/pyproject.toml
sdks/blue-krill/README.md
sdks/blue-krill/pyproject.toml
sdks/paas-service/pyproject.toml

- Change the license of every package to "MIT"
- Add "readme", "author" and other related metadata

Update metainfo of every package, fix #1

---

sdks/bkpaas-auth/bkpaas_auth/backends.py
sdks/bkpaas-auth/bkpaas_auth/core/http.py
sdks/bkpaas-auth/bkpaas_auth/core/services.py
sdks/bkpaas-auth/bkpaas_auth/core/token.py
sdks/bkpaas-auth/bkpaas_auth/monkey.py
sdks/bkpaas-auth/bkpaas_auth/utils.py
sdks/bkpaas-auth/tests/conftest.py
sdks/bkpaas-auth/tests/test_utils.py

- bkpaas-auth: Remove or mask sensitive data in the logging messages

bkpaas-auth: Remove or mask sensitive data in the logging messages

---

sdks/bkpaas-auth/pyproject.toml
sdks/bkpaas-auth/setup.py

chore: update bkpaas-auth version

---

sdks/apigw-manager/src/apigw_manager/apigw/management/commands/fetch_apigw_public_key.py
sdks/apigw-manager/src/apigw_manager/apigw/management/commands/fetch_esb_public_key.py
sdks/apigw-manager/tests/apigw_manager/apigw/management/commands/test_fetch_esb_public_key.py

- fix Command fetch_esb_public_key params error

fix fetch_esb_public_key command

---

sdks/blue-krill/blue_krill/models/better_loaddata/management/commands/better_loaddata.py

Add docstring for "better_loaddata" command

Add docstring for "better_loaddata" command

---

sdks/blue-krill/pyproject.toml

- Loosen the version constraints of some deps.

Loosen the version constraints of some deps.

---

sdks/apigw-manager/README.md

git push --set-upstream origin feat-apigw-manager-doc-fix-stage-plugins

doc: fix apigw stage plugin config

---

sdks/apigw-manager/README.md
sdks/apigw-manager/examples/chart/use-configmap/files/support-files/resources.yaml
sdks/apigw-manager/examples/chart/use-custom-docker-image/my-apigw-manager/support-files/resources.yaml

doc: support stage backends

---

sdks/apigw-manager/docs/sync-apigateway-with-docker.md
sdks/apigw-manager/examples/chart/use-configmap/values.yaml
sdks/apigw-manager/examples/chart/use-custom-docker-image/my-apigw-manager/Dockerfile

fix apigw-manager image version

doc: fix image version

---

sdks/apigw-manager/docs/sync-apigateway-with-docker.md
sdks/apigw-manager/examples/chart/use-configmap/values.yaml
sdks/apigw-manager/examples/chart/use-custom-docker-image/my-apigw-manager/Dockerfile

feat: update docker image version

---

sdks/apigw-manager/docs/sync_apigateway.md

fix: fix apigw doc link

---

sdks/apigw-manager/README.md
sdks/apigw-manager/docs/sync-apigateway-with-django.md
sdks/apigw-manager/docs/sync-apigateway-with-docker.md
sdks/apigw-manager/src/apigw_manager/apigw/management/commands/sync_apigw_resources.py
sdks/apigw-manager/tests/apigw_manager/apigw/management/commands/test_sync_apigw_resources.py

feat(apigw/sync_resource): support doc

---

sdks/apigw-manager/src/apigw_manager/apigw/management/commands/sync_apigw_resources.py

fix(apigw/sync_resource): fix bug

fix(apigw/sync_resource): fix bug

---

sdks/apigw-manager/pyproject.toml
sdks/apigw-manager/src/apigw_manager/apigw/authentication.py
sdks/apigw-manager/src/apigw_manager/core/handler.py
sdks/apigw-manager/src/apigw_manager/drf/authentication.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_authentication.py

- middleware 中 request.app/request.user 增加租户相关信息
- 调用网关接口指定一个占位的 `X-Bk-Tenant-Id` 以通过校验

fix(tenant): add tenant mode/id for jwt app, and tenant_id for jwt user

---

pyproject.toml
sdks/blue-krill/CHANGE.md
sdks/blue-krill/blue_krill/__init__.py
sdks/blue-krill/blue_krill/auth/jwt.py
sdks/blue-krill/blue_krill/data_types/enum.py
sdks/blue-krill/blue_krill/storages/blobstore/s3.py
sdks/blue-krill/poetry.lock
sdks/blue-krill/pyproject.toml
sdks/blue-krill/tests/async_utils/test_poll_task.py
sdks/blue-krill/tests/editions/test_editionctl.py
sdks/blue-krill/tests/storages/conftest.py

- chore: blue-krill v2.1.0 & some minor enhancements

chore: blue-krill v2.1.0 & some minor enhancements

---

sdks/apigw-manager/src/apigw_manager/plugin/config.py
sdks/apigw-manager/tests/apigw_manager/plugin/test_config.py

feat(apigw_manager/plugin): 新增 response_rewrite 和 redirect 插件的 build 函数

feat(apigw_manager/plugin): 新增 response_rewrite 和 redirect 插件的 build 函数

---

sdks/apigw-manager/pyproject.toml
sdks/apigw-manager/src/apigw_manager/drf/management/commands/data/definition.yaml

feat(apigw-manager/definition.yaml): support env vars

---

sdks/apigw-manager/CHANGE.md
sdks/apigw-manager/pyproject.toml
sdks/apigw-manager/src/apigw_manager/apigw/utils.py
sdks/apigw-manager/src/apigw_manager/core/configuration.py
sdks/apigw-manager/src/apigw_manager/core/handler.py
sdks/apigw-manager/tests/apigw_manager/apigw/test_utils.py
sdks/apigw-manager/tests/apigw_manager/core/test_hander.py

use BK_APP_TENANT_ID or BKPAAS_APP_TENANT_ID as X-Bk-Tenant-Id

feat(apigw_manager/config): add BK_APP_TENANT_ID

---

sdks/apigw-manager/src/apigw_manager/plugin/config.py
sdks/apigw-manager/tests/apigw_manager/plugin/test_config.py

feat(apigw_manager/plugin): 新增 bk-username-required 插件

feat(apigw_manager/plugin): 新增 bk-username-required 插件
